[package]
name = "dyn_vs_func_ptr_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.3.5"
