[package]
name = "str_utf8_aware_offset"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]
criterion = "0.5.1"
