[package]
name = "advent_of_code_2022"
publish = false
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"
path = "1.rs"

[[bin]]
name = "2"
path = "2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
